
import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import { supabase } from '../../util/supabase'
import { useEffect, useState } from 'react'
import { pokemonType } from '../../types/pokemon'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [pokemons, setPokemon] = useState<Array<pokemonType>>()
  async function getPokemons() {
    let { data: pokemon, error } = await supabase
      .from('Pokemon')
      .select('*')
      // @ts-ignore
    setPokemon(pokemon)
  }
  useEffect(() => {
    getPokemons()
  }, [])

  if (!pokemons) {
    return (
      <main className={styles.main}>
        <h1>Loading ....</h1>
      </main>)
  }
  return (
    <>
      <Head>
        <title>CSR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={inter.style}>Client side generated page</h1>
        <div className={styles.center} style={inter.style}>
          <h3>This page was generated on</h3>
          <h5>{new Date().toString()}</h5>
          <br />
          <h2>Pokemons</h2>
          <ul>
            {pokemons?.map((pokemon) =>
            (<div key={pokemon.id}>
              <Link href={`CSR/${pokemon.id}`}>{pokemon.name}</Link>
            </div>)
            )}
          </ul>
        </div>
      </main>
    </>
  )
}
