import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import { supabase } from '../../util/supabase'
import { pokemonType } from '../../types/pokemon'

const inter = Inter({ subsets: ['latin'] })

export default function ISR(props: { timeStamp: string, pokemons: Array<pokemonType> }) {
  return (
    <>
      <Head>
        <title>ISR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={inter.style}>Incrementally static generated page</h1>
        <div className={styles.center} style={inter.style}>
          <h3>This page was generated on</h3>
          <h5>{props?.timeStamp}</h5>
          <br />
          <h2>Pokemons</h2>
          <ul>
            {props.pokemons.map((pokemon) =>
            (<div key={pokemon.id}>
              <Link href={`ISR/${pokemon.id}`}>{pokemon.name}</Link>
            </div>)
            )}
          </ul>
        </div>
      </main>
    </>
  )
}
export async function getStaticProps() {
  const { data: pokemons } = await supabase.from("Pokemon").select("*").order('id', { ascending: true });
  const timeStamp = await new Date().toString()
  return {
    props: {
      timeStamp,
      pokemons
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  }
}
